src/App.jsx, src/components/certification/CertificationBanner.jsx, src/components/certification/CertificationCard.jsx, src/components/certification/LearningModule.jsx, src/components/layout/Header.jsx, src/components/layout/MainLayout.jsx, src/components/layout/Sidebar.jsx, src/pages/LearningContent.jsx
This PR implements the **Sidebar**, **MainLayout**, **Header**, and **LearningContent** components as per the Figma design provided. These components are essential for structuring the application layout and ensuring a consistent user experience.
1. **Sidebar**: Includes navigation links and visual elements from the design.
2. **MainLayout**: Provides a structured layout for all pages.
3. **Header**: Contains branding, navigation, and user profile details.
4. **LearningContent**: Displays the main content for the Learning page as per the design.
- Created the following files:
- `components/layout/Sidebar.jsx`
- `components/layout/MainLayout.jsx`
- `components/layout/Header.jsx`
- `pages/LearningContent.jsx`
- Styled components using **Tailwind CSS** to match the Figma design.
- Tested …
=>  feat:create-sidebar-mainlayout-header-learning-page

src/App.jsx, src/pages/StarklaChat.jsx
This PR introduces enhanced styling for the Starkla chat interface to improve the user experience and align with the overall design system. The updates include a more modern and cohesive look, better readability, and improved responsiveness.
- Updated the chat container styling to match the application's theme.  
- Improved the text input area for better usability.  
- Enhanced the chat bubble design for both user and Starkla messages.  
- Added responsive design adjustments for different screen sizes.  
- Implemented subtle animations for message transitions.  
1. Navigate to the Starkla chat interface.  
2. Send a message and observe the new chat bubble styling.  
3. Resize the browser window to check responsiveness.  
4. Verify that animations for message transitions are smooth.  
---
=> Enhancement-Starkla-update-style

src/components/layout/Sidebar.jsx
- Added the `clickedButton` state to track the clicked button and provide visual feedback.
- Implemented the `handleButtonClick` function to handle button clicks and update the state.
- Updated the class names for main buttons and sub-buttons to dynamically change to blue only after being clicked.
- The blue color persists until another button is clicked or the page is refreshed.
- Ensured compatibility with existing functionality.
=> feat: update biutton in sidebar

src/App.jsx, src/pages/HomePage.jsx, src/pages/WalletConnection.jsx
This PR introduces the implementation of the **Homepage** and **Connect Wallet Page** as outlined in Issue #[Insert Issue Number Here]. The changes include:
- Creation of the Homepage with a responsive layout and navigation.
- Development of the Connect Wallet Page with wallet integration functionality.
- Responsive design for both pages to ensure compatibility across devices.
- Added `Homepage.jsx` for the main landing page.
- Added `ConnectWalletPage.jsx` for wallet connection functionality.
- Updated `App.js` to include routing for the new pages.
- Added necessary styles in `Homepage.css` and `ConnectWalletPage.css`.
- Integrated wallet connection SDK for supported wallets.
- Tested wallet connection functionality with supported wallets.
- Verified responsive design on desktop, tablet, …
=> Feature home page wallet connection

package-lock.json, package.json, src/pages/StarklaChat.jsx
Add Upload Files to Chat with Starkla and Use the File Icon
**Closes:** #20  
**Related Issue:** [Add Upload Files to Chat with Starkla and Use the File Icon](#20)  
---
This PR adds the ability to upload files directly to the chat interface. The feature integrates with Starkla for secure file handling and storage, and a file icon is added to the UI to represent the upload option. This enhancement improves user experience by allowing seamless sharing of documents, images, and other file types within the chat.
---
- Added a file upload button (file icon) to the chat interface.  
- Integrated file upload functionality with Starkla for secure processing and storage.  
- Supported file types: PDF, DOCX, PNG, JPG, and TXT.  
- Added error handling for unsupported file types and failed uploads. …
=> Feature:Upload files in chat

package-lock.json, package.json, src/App.jsx, src/pages/StarklaChat/StarklaChat.jsx, src/pages/StarklaChat/StarklaChat.module.css
Improvements were made to the chat, optimizing its design and functionality. Messages were styled with shadows, rounded borders, and consistent alignments: user messages on the right and Eliza's messages on the left. The text input field was repositioned to remain fixed at the bottom, and interactive elements such as buttons for file uploads and voice input were added.
Additionally, ElizaBot was integrated as the base for responses, and a "thinking" animation with blinking dots was implemented while generating a reply.
https://github.com/user-attachments/assets/8fc1cdcc-dfba-4ce5-b250-8b32ca7a8a3d
=> feat: eliza chat implemented

package-lock.json, package.json, src/pages/WalletConnection.jsx
This PR implements the **Connect Your Wallet Page** as described closes issue #13  . The page allows users to connect their Starknet wallets (e.g., ArgentX or Braavos) securely and seamlessly. The implementation includes a responsive layout, wallet connection functionality, and error handling.
1. Created a new file `pages/ConnectWallet.jsx` for the Connect Your Wallet Page.
2. Implemented the layout and styling using Tailwind CSS.
3. Added wallet connection functionality using the Starknet library.
4. Included error handling for wallet connection issues.
5. Ensured the page is responsive and visually consistent with the Figma design.
- **Wallet Detection**: Checks if a Starknet wallet (e.g., ArgentX or Braavos) is installed.
- **Secure Connection**: Uses `window.starknet.enable()` to …
=> Create Connect Your Wallet Page

src/components/layout/Sidebar.jsx, src/pages/GrammarContent.jsx, src/pages/LearningContent.jsx
Updated the UI adding categories, more pages as well as the choose your level. The functionality of the buttons will be gone and needs to be added.
This issue closes #35 
close #35
=> UI-Adding-Categories

src/components/layout/Footer.jsx, src/components/layout/MainLayout.jsx, src/pages/HomePage.jsx
This PR addresses **[Issue #43](https://github.com/STARKLAOrg/STARKLA-Frontend/issues/43)** by implementing the following changes:
- **Create footer:** Fixed footer moved with the same details as the previous one.
- **Responsive Design**
- **New footer is anchored to the page layout**
---
---
1. **Analysis & Planning:** 30 minutes
2. **Footer Implementation:** 1 hour
3. **Testing & Debugging:** 15 minutes
4. **Documentation & PR Creation:** 20 minutes
---
---
**Let me know if there are any additional settings or specific links to include in the footer!**
=> Bug: The footer layout needs to be adjusted

src/components/layout/Header.jsx, src/components/layout/Sidebar.jsx
Brief description of the changes made to the Header and Sidebar component.
- Centered search bar using absolute positioning
- Implemented custom tooltip functionality
- Removed text from settings button
- Added hover state for navigation buttons
https://www.loom.com/share/349aec1d5e0f46be9eceb3beaa5bb741?sid=2341f50b-0c16-466e-bcd5-d42816dfc8cd
=> Issue 46 restructure nav layout

package-lock.json, package.json, src/App.jsx, src/components/layout/Header.jsx, src/components/ui/ConnectWalletButton.jsx, src/context/WalletContext.jsx, src/main.jsx, src/utils/helpers.jsx
Implement a wallet connection system in the header using StarkNet Kit, replacing the separate connection page and improving the user experience.
- **"Connect Wallet" button** in the header with dynamic states
- Automatic reconnection on page reload
- Centralized wallet state management using React Context
- Responsive design consistent with the app's theme
**Purpose:** A reusable button component for connecting and disconnecting the wallet.
**Features:**
- Dynamically displays "Connect Wallet" or the truncated wallet address.
- Inverted hover effect (black ↔ white).
- Integrates with the global wallet context for state management.
- Uses the Wallet icon from lucide-react.
**Purpose:** The main header component updated to include the wallet connection button.
**Changes:**
- Added the …
=> Add wallet connect button 

src/App.jsx, src/components/layout/Header.jsx, src/pages/Notifications.jsx
In this development, we implemented a notification system for the Starkla platform, including:
1. **Bell icon with an unread notification counter** in the header.
2. **Dropdown notification menu**, with an option to mark all as read.
3. **Notification Center (/notifications)** with filters to view all, unread, or read notifications.
- **Modified the header (`Header`)** to include the notification icon with a dynamic `badge`.
- **Added click functionality on notifications**, redirecting to the notification center.
- **Created the `NotificationCenter` page**, with a clean design and filtering options.
- React + Vite
- Tailwind CSS
- React Router
- **Display notifications in a dropdown menu.**
- **Mark all notifications as read.**
- **Filter notifications on the notification center page.** …
=> feat: create notification page

package-lock.json, package.json, src/App.jsx, src/components/practice/DragDropSentenceBuilder.jsx
This PR introduces a fully interactive drag-and-drop sentence-building component. The feature allows users to construct sentences by dragging words into a designated area, rearranging them, and receiving instant grammar validation.
Closes #49
=> feat: Implement drag-and-drop sentence-building component with grammar validation

src/App.jsx, src/components/quiz/FillInTheBlanksQuiz.jsx, src/pages/FillInTheBlanksQuizPage.jsx
https://www.loom.com/share/9b729cb4126e4dc4b2873d80a1c9704e?sid=2dfd1784-59e4-4641-b0fe-cdb231f39d69
Implemented a new Fill in the Blanks Quiz feature with 10 questions, instant validation, hint system, and scoring mechanism. The feature provides an interactive way for users to test their knowledge through completing sentences or phrases.
1. `FillInTheBlanksQuiz.jsx` - Main quiz component with:
- 10 pre-configured questions with answers and hints
- Input validation and instant feedback
- Score tracking and color-coded results
- Hint system for each question
- Responsive design with Tailwind CSS
2. `FillInTheBlanksQuizPage.jsx` - Page wrapper component with:
- Header and instructions
- Quiz component integration
- Responsive layout
1. **Quiz Structure**:
- 10 fill-in-the-blank questions
- …
=> feat: impl fill the blanks quiz

docs/user_recognition_system.md
Closes https://github.com/STARKLAOrg/STARKLA-Frontend/issues/67
=> docs: add user recognition system documentation

src/components/layout/Sidebar.jsx
=> Deleting settings and questions buttons from sidebar component

src/components/layout/Sidebar.jsx, src/components/layout/main-layout.jsx
closes #93 
- During development, I temporarily commented out unfinished components to focus on the current work. Once the required components were completed, I reintegrated them by uncommenting the code.
- I added the correct imports in the main-layout.jsx file 
[Screencast from 2025-02-22 00-23-08.webm](https://github.com/user-attachments/assets/5e7f7b9e-efdc-4d8a-a97e-a19994633ec9)
@zleypner kindly review
=> feat: add Home button to Sidebar and update component imports

src/components/layout/Footer.jsx, src/components/layout/Header.jsx, src/components/layout/Sidebar.jsx, src/components/layout/main-layout.jsx, src/components/layout/ui/connect-wallet-button.jsx, src/pages/aurora-site/analytics.jsx, src/pages/aurora-site/community/community.jsx, src/pages/aurora-site/grammar-content.jsx, src/pages/aurora-site/learning/listening-content.jsx, src/pages/aurora-site/learning/reading-content.jsx, src/pages/aurora-site/learning/speaking-content.jsx, src/pages/aurora-site/learning/vocabulary-content.jsx, src/pages/aurora-site/settings/index.jsx
Change the color of the platform like blue , the buttons etc
basically did a change to header, sidebar and footer component
=> fix-changed color component for footer

src/pages/aurora-site/aurora-chat/custom-audio-player.jsx, src/pages/aurora-site/aurora-chat/file-preview-modal.jsx, src/pages/aurora-site/aurora-chat/index.jsx, src/pages/aurora-site/aurora-chat/render-file-upload-message.jsx
❗ **Pull Request Information**
This PR implements file preview for the AI chat panel.
File Upload Handling: Enhanced the _handleFileUpload_ function to provide better previews for different file types:
- Images: Display a thumbnail in the chat.
- Audio: Include a basic audio player in the message.
- Text files (TXT, PDF, etc.): Show a preview box with the file's content. For PDFs, display the file using the embed tag.
Rendering Message Content: Added the _renderMessageContent_ function to handle the new file previews:
Images: Displayed as thumbnails.
Audio: Displayed with an audio player.
Text files: Displayed in a pre tag for text files and using the embed tag for PDFs.
- **Video**: [Link to Loom video](https://www.loom.com/share/126410d097754c10ac2613891fdafe96?sid=6d547328-bb65-4cd7-b71 …
=> feat(chat): improve file upload handling and message rendering/preview

src/components/community/ai-practice-tab.jsx, src/components/community/call-to-action.jsx, src/components/community/events-tab.jsx, src/components/community/forums-tab.jsx, src/components/community/header.jsx, src/components/community/hero-section.jsx, src/components/community/stats-bar.jsx, src/components/community/study-groups-tab.jsx, src/components/community/success-stories.jsx, src/components/community/tabs-section.jsx, src/components/ui/avatar.jsx, src/components/ui/badge.jsx, src/components/ui/button.jsx, src/components/ui/card.jsx, src/components/ui/input.jsx, src/components/ui/separator.jsx, src/components/ui/tabs.jsx, src/data/mock-data-community.jsx, src/lib/utils.jsx, src/pages/aurora-site/community/community.jsx
This PR implements the full layout for the **Community Page** in the Aurora frontend. The page is composed using modular components for clarity and reuse. It covers the visual and structural setup only — data integration will be handled later.
---
- **CommunityPage Layout:**  
Assembled the page using multiple subcomponents to separate concerns and improve readability.
- **Header:**  
Top-level navigation or branding element.
- **HeroSection + StatsBar:**  
Introduced a blue-highlighted section with a brief hero message and a stats bar showing metrics like active students, satisfaction, and number of tools.
- **TabsSection:**  
Built a tabbed interface allowing navigation between:
- Forums  
- Events  
- Study Groups  
- AI Practice
Each tab is connected to its own file (`forums-tab.jsx`, …
=> Feat: implement community page

package-lock.json, src/App.jsx, src/components/Games/word-matching/game-board.jsx, src/components/layout/Footer.jsx, src/components/layout/Sidebar.jsx, src/pages/aurora-site/modules/module-details.jsx, src/pages/games/story-game/index.jsx, src/pages/games/word-matching/index.jsx
Pull Request Description
Title :
feat: Update Sidebar and Footer to Match Figma Design
Description
This PR updates the sidebar navigation and footer components to align with the provided Figma design. The following changes have been implemented:
Sidebar Updates :
Removed the level option and its related functionality as per the requirements.
Updated the navigation items to match the Figma design, removing any items not present in the design.
Ensured all text is in English and removed any translation-related functionality.
Applied styling updates to match the Figma design specifications, including spacing, typography, and layout.
Tested responsiveness on mobile, tablet, and desktop screen sizes.
Footer Updates :
Redesigned the footer to visually align with the updated sidebar styling. …
=> Making Changes to Footer and Sidebar.

src/components/auth/login-form.jsx, src/components/auth/protected-route.jsx, src/components/layout/Header.jsx, src/components/layout/main-layout.jsx, src/context/AuthContext.jsx
❗ **Pull Request Information**
This pull request addresses a series of critical issues related to authentication flow, navigation, and content rendering within the Aurora  platform. It includes backend and frontend adjustments to ensure a seamless and consistent user experience.
---
- Refactored `AuthContext` to properly persist the authentication token using `localStorage`.
- Updated the login response to return a flat `user` object instead of a nested `userResponse`.
- Enhanced the `useEffect` inside `AuthProvider` to load the current user from `/auth/me` if a token is found.
- Added a route mapping system in the `Header` component to prevent navigation to undefined paths.
- Refactored all navigation buttons in both `Header` and `Sidebar` to only target valid routes defined in …
=> Fix: auth layout behavior

src/App.jsx, src/components/Games/word-scramble/word-scramble-game.jsx, src/pages/games/story-game/index.jsx, src/pages/games/word-matching/index.jsx
**📍 Location:** `AURORA-Frontend\src\components\homepage`
This PR updates the homepage structure and adds new components to enhance the user experience.
- Updated homepage layout/structure
- Added new components for homepage functionality
- Improved existing component organization
- To implement the new homepage design
- To add missing components required for full functionality
- To improve code organization and maintainability
[Before/After screenshots or component previews]
Closes #143  (if applicable)
💡 **Note:** Please review the component structure and let me know if any adjustments are needed!
=> Fix: fix homepage

src/App.jsx
=> se quita el protected mode para poder abrir diferentes rutas sin login

src/App.jsx
=> para que no lo pida en los otros lados

src/App.jsx, src/components/practices/funny_practices/DragDropSentenceBuilder.jsx
=> add drag-and-drop sentence builder

src/components/landing-page/call-to-action/CallToAction.jsx, src/components/landing-page/call-to-action/Cards.jsx, src/components/landing-page/call-to-action/responsive.css
Responsive landing page
https://github.com/user-attachments/assets/46a8e837-733e-4df8-8bec-faf3e3230355
=> Responsive landing page

src/App.jsx, src/components/practices/funny_practices/FillInTheBlanksPage.jsx, src/components/practices/funny_practices/FillInTheBlanksQuiz.jsx, src/components/practices/funny_practices/Quiz.jsx, src/components/practices/funny_practices/QuizPage.jsx, src/components/practices/funny_practices/SentenceBuilder.jsx
add some components , routes etc 
works fine :)
=> added sentence builder & fill in the blancks & quiz

src/App.jsx
=> added some practices

src/components/ui/practiceDropdown.jsx
=> added routes for practice button

src/App.jsx, src/hooks/use-header.jsx
Closes #[issue-number]
- [x ] 🔧 Refactoring
- [x ] 🧹 Chore
=> add word-scramble route

src/components/layout/Sidebar.jsx, src/components/layout/header/header.jsx, src/components/layout/header/nav-desktop.tsx, src/components/layout/main-layout.jsx, src/hooks/use-header.jsx
Closes #[issue-number]
- [ x] 🐛 Bug fix
- [x ] 🔧 Refactoring
=> fix sidebar,added route for notifications,setting and analytics buttons
